##### Required Packages

In [1]:
import numpy as np
from numpy.linalg import inv
from scipy.linalg import lu

#### Apply the Jacobi and Gauss-Seidel method to solve
- 𝟓𝒙𝟏−𝟐𝒙𝟐+𝟑𝒙𝟑=−𝟏, −𝟑𝒙𝟏+𝟗𝒙𝟐+𝒙𝟑=𝟐, 𝟐𝒙𝟏−𝒙𝟐−𝟕𝒙𝟑=𝟑
- Solve once without vectorization then use vectorize implementation.
- Check for convergance.
- Use different tolerence and see the difference between the two methods. e.g. tol: 0.01,0.001,0.0001 ... etc.

#### Jacobi not Vectorized

##### Step 1: Check Type of Matrix (Convergence check)

In [2]:
def matrixType(A):
    D = np.zeros((A.shape), int)
    np.fill_diagonal(D, np.diag(A))

    np.abs(np.diag(A))
    print(D)

    diagonal = np.abs(np.diag(A))
    print(diagonal)

    off_diagonal = np.sum(np.abs(A)[~np.eye(np.abs(A).shape[0],dtype=bool)].reshape(3,2), axis=1)
    print(off_diagonal)

    if(np.all(diagonal > off_diagonal)):
        print("Strictly Dominant")

    elif(np.all(diagonal >= off_diagonal)):
        print("Diagonally Dominant")
        
    elif(np.any(diagonal < off_diagonal)):
        print("Non-diagonally Dominant")

##### Step 2: Implement Jacobi (Non-vectorized)

In [3]:
def jacobi_non_vectorized(A, epsilon=0.00001):

    x1, x2, x3 = [0.0], [0.0], [0.0]
    print("k,\tx1,\tx2,\tx3")
    
    for i in range(1000):
        
        if (len(x1) > 2):
            error = np.linalg.norm([np.abs(x1[i]-x1[i-1]), np.abs(x2[i]-x2[i-1]), np.abs(x3[i]-x3[i-1])])
            if error <= epsilon:
                print("Converged")
                break
            else:
                print(i, end="\t")
        else:
            print(i, end="\t")
        
        print(np.round(x1[i], 4), end="\t")
        print(np.round(x2[i], 4), end="\t")
        print(np.round(x3[i], 4), end="\t")
        print("\n")
        
        x1.append(((2 * x2[i - 1]) - (3 * x3[i - 1]) - 1) / (5))
        x2.append(((3 * x1[i - 1]) - x3[i - 1] + 2) / (9))
        x3.append(((-2 * x1[i - 1]) + x2[i - 1] +3) / (-7))

##### Step 3: Test Function

In [4]:
A = np.array([[5, -2, 3], [-3, 9, 1], [2, -1, -7] ])
matrixType(A)
print("---------------------------")
jacobi_non_vectorized(A=A)

[[ 5  0  0]
 [ 0  9  0]
 [ 0  0 -7]]
[5 9 7]
[5 4 3]
Diagonally Dominant
---------------------------
k,	x1,	x2,	x3
0	0.0	0.0	0.0	

1	-0.2	0.1556	-0.5079	

2	-0.2	0.2222	-0.4286	

3	0.167	0.212	-0.5079	

4	0.146	0.2032	-0.5175	

5	0.1896	0.3343	-0.4111	

6	0.1917	0.3284	-0.4159	

7	0.1804	0.3311	-0.4222	

8	0.1809	0.3323	-0.4207	

9	0.1857	0.3293	-0.4243	

10	0.1854	0.3293	-0.4244	

11	0.1863	0.3313	-0.4225	

12	0.1863	0.3312	-0.4226	

13	0.186	0.3313	-0.4227	

14	0.1861	0.3313	-0.4226	

15	0.1861	0.3312	-0.4227	

Converged


#### Jacobi Vectorized

In [5]:
def jacobi_vectorized(A, Y, epsilon=0.00001):
    
    D = np.zeros((A.shape), int)
    np.fill_diagonal(D, np.diag(A))

    D_inv = inv(D)
    L = -np.tril(A, -1)
    U = np.triu(A, 1)

    T = (D_inv) @ (L - U)
    C = np.ravel(D_inv @ Y)

    print("k,\tx1,\tx2,\tx3")

    X = np.zeros(A.shape[1])

    for i in range(1, 1000):
        
        last_X = np.copy(X)
        
        print(i, end="\t")
        
        X = T @ last_X + C
        print(*np.round(X, 4), sep="\t")
        
        if (np.abs(X - last_X) < epsilon).all():
            print("Converged")
            break

In [6]:
A = np.array([[5, -2, 3], [-3, 9, 1], [2, -1, -7]])
Y = np.array([ [-1], [2], [3] ])
jacobi_vectorized(A=A, Y=Y)

k,	x1,	x2,	x3
1	-0.2	0.2222	-0.4286
2	0.146	0.2032	-0.5175
3	0.1917	0.3284	-0.4159
4	0.1809	0.3323	-0.4207
5	0.1854	0.3293	-0.4244
6	0.1863	0.3312	-0.4226
7	0.1861	0.3313	-0.4226
8	0.1861	0.3312	-0.4227
9	0.1861	0.3312	-0.4227
10	0.1861	0.3312	-0.4227
Converged
