#### Required Packages

In [1]:
import numpy as np
from numpy.linalg import inv
from scipy.linalg import lu

### Solve the following system of equations using LU Decomposition method:
#### Find L and U by hand.
#### Confirm that A=LU then solve.
- Ex1. 𝟐𝒙+𝟓𝒚=𝟐𝟏, 𝒙+𝟐𝒚=𝟖.
- Ex2. 𝒙𝟏+𝒙𝟐+𝒙𝟑=𝟏, 𝟒𝒙𝟏+𝟑𝒙𝟐−𝒙𝟑=𝟔, 𝟑𝒙𝟏+𝟓𝒙_𝟐+𝟑𝒙𝟑=𝟒

#### Use scipy.linalg.lu() to slove the previous system using LU decomposition and compare the results.

### Note (when using scipy):
- In the second system of equations We can see the <b>L and U</b> we get are different from the ones we got by hand. 
- You will also see there is a permutation matrix <b>P</b> that returned by the <b>lu function</b>. 
- This permutation matrix record how do we change the order of the equations for easier calculation purposes (for example, if first element in first row is zero, it can not be the pivot equation, since you can not turn the first elements in other rows to zero. Therefore, we need to switch the order of the equations to get a new pivot equation). 
- If you multiply <b>P with A</b>, you will see that this permutation matrix effect.
- You will need to arrange the ouput based on the new matrix <b>A</b> achieved by <b>LU</b> multiplication in order to correctly solve the system of equations.

In [32]:
def printResult(**matrices):
    for label, matrix in matrices.items():
        print("Matrix({}) Dim: ".format(label), matrix.shape, "\n", matrix, end="\n-----------------------------------------------\n")
#################################################################################
def LU_DEC(A, Y):
    P, L, U = lu(A)
    Y = inv(P) @ Y
    LU = L.dot(U)
        
    M = inv(L) @ Y
    X = inv(U) @ M

    printResult(A=A, L=L, U=U, P=P, Y=Y, LU=LU, M=M, X=X)

- ##### Ex1. 𝟐𝒙+𝟓𝒚=𝟐𝟏, 𝒙+𝟐𝒚=𝟖.

In [33]:
A = np.array([ [2,5], [1,2] ])
Y = np.array([ [21], [8] ])
LU_DEC(A, Y)

Matrix(A) Dim:  (2, 2) 
 [[2 5]
 [1 2]]
-----------------------------------------------
Matrix(L) Dim:  (2, 2) 
 [[1.  0. ]
 [0.5 1. ]]
-----------------------------------------------
Matrix(U) Dim:  (2, 2) 
 [[ 2.   5. ]
 [ 0.  -0.5]]
-----------------------------------------------
Matrix(P) Dim:  (2, 2) 
 [[1. 0.]
 [0. 1.]]
-----------------------------------------------
Matrix(Y) Dim:  (2, 1) 
 [[21.]
 [ 8.]]
-----------------------------------------------
Matrix(LU) Dim:  (2, 2) 
 [[2. 5.]
 [1. 2.]]
-----------------------------------------------
Matrix(M) Dim:  (2, 1) 
 [[21. ]
 [-2.5]]
-----------------------------------------------
Matrix(X) Dim:  (2, 1) 
 [[-2.]
 [ 5.]]
-----------------------------------------------


- ##### Ex2. 𝒙𝟏+𝒙𝟐+𝒙𝟑=𝟏, 𝟒𝒙𝟏+𝟑𝒙𝟐−𝒙𝟑=𝟔, 𝟑𝒙𝟏+𝟓𝒙_𝟐+𝟑𝒙𝟑=𝟒

In [34]:
A = np.array([[1, 1, 1], [4, 3, -1], [3, 5, 3]])
Y = np.array([[1],[6], [4]])
LU_DEC(A, Y)

Matrix(A) Dim:  (3, 3) 
 [[ 1  1  1]
 [ 4  3 -1]
 [ 3  5  3]]
-----------------------------------------------
Matrix(L) Dim:  (3, 3) 
 [[1.         0.         0.        ]
 [0.75       1.         0.        ]
 [0.25       0.09090909 1.        ]]
-----------------------------------------------
Matrix(U) Dim:  (3, 3) 
 [[ 4.          3.         -1.        ]
 [ 0.          2.75        3.75      ]
 [ 0.          0.          0.90909091]]
-----------------------------------------------
Matrix(P) Dim:  (3, 3) 
 [[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
-----------------------------------------------
Matrix(Y) Dim:  (3, 1) 
 [[6.]
 [4.]
 [1.]]
-----------------------------------------------
Matrix(LU) Dim:  (3, 3) 
 [[ 4.  3. -1.]
 [ 3.  5.  3.]
 [ 1.  1.  1.]]
-----------------------------------------------
Matrix(M) Dim:  (3, 1) 
 [[ 6.        ]
 [-0.5       ]
 [-0.45454545]]
-----------------------------------------------
Matrix(X) Dim:  (3, 1) 
 [[ 1. ]
 [ 0.5]
 [-0.5]]
--------------------------