##### Required Packages

In [1]:
import numpy as np
from numpy import linalg as LA
import pandas as pd

In [2]:
def power_method(A):
    
    X = np.ones((A.shape[0], 1), int)
    past = np.ones((A.shape[0], 1), int)
    
    epsilon = 0.000001
    n_iter = 0
    for i in range(12):
        past = X
        
        res = A.dot(X)
        largest_lambda = LA.norm(res, np.inf)
        print("Lambda: ", largest_lambda)
        res = (res / LA.norm(res, np.inf))
        X = res
        n_iter+=1
        if i > 0 and LA.norm(past - X) <= epsilon:
            break
        print("Iteration ", i, "\n",X, "\n")
    return largest_lambda, X, n_iter


#### PageRank

In [3]:
p = np.array([[0 , 0 , 0.25 , 0 , 0],
            [1 , 0 , 0.25 , 0 , 0 ],
            [0 , 0 ,   0 , 0.5, 0 ],
            [0 , 0 , 0.25 , 0 , 1 ],
            [0 , 1 , 0.25 ,.5 , 0]])

In [4]:
nodes = np.array([4, 5, 3, 2, 1])

In [5]:
lambda_, ranks, iterations = power_method(p)

Lambda:  1.75
Iteration  0 
 [[0.14285714]
 [0.71428571]
 [0.28571429]
 [0.71428571]
 [1.        ]] 

Lambda:  1.1428571428571428
Iteration  1 
 [[0.0625]
 [0.1875]
 [0.3125]
 [0.9375]
 [1.    ]] 

Lambda:  1.078125
Iteration  2 
 [[0.07246377]
 [0.13043478]
 [0.43478261]
 [1.        ]
 [0.68115942]] 

Lambda:  0.7898550724637682
Iteration  3 
 [[0.13761468]
 [0.2293578 ]
 [0.63302752]
 [1.        ]
 [0.93577982]] 

Lambda:  1.0940366972477065
Iteration  4 
 [[0.14465409]
 [0.27044025]
 [0.45702306]
 [1.        ]
 [0.81132075]] 

Lambda:  0.9255765199161425
Iteration  5 
 [[0.12344281]
 [0.2797282 ]
 [0.54020385]
 [1.        ]
 [0.95583239]] 

Lambda:  1.0908833522083805
Iteration  6 
 [[0.12379964]
 [0.23695821]
 [0.45834415]
 [1.        ]
 [0.83856735]] 

Lambda:  0.9531533869711913
Iteration  7 
 [[0.12021784]
 [0.25010211]
 [0.52457454]
 [1.        ]
 [0.89339687]] 

Lambda:  1.0245405037440434
Iteration  8 
 [[0.12800239]
 [0.24534069]
 [0.48802365]
 [1.        ]
 [0.86013754]] 



In [6]:
print(lambda_)

0.9964743790931728


In [7]:
ranks

array([[0.12415248],
       [0.25056221],
       [0.50176905],
       [1.        ],
       [0.87571313]])

In [8]:
df = pd.DataFrame(ranks, columns=['ranks'], index=np.arange(1,6))
df

ranks
1  0.124152
2  0.250562
3  0.501769
4  1.000000
5  0.875713