##### Required Packages

In [1]:
import numpy as np
from numpy import linalg as LA

### Use power method to find the largest eigenvalue and the corresponding eigenvector of the matrices:
$$\begin{bmatrix} 0 & 2 \\ 2 & 3\end{bmatrix}$$

$$\begin{bmatrix} -4 & 14 & 0 \\ -5 & 13 & 0 \\ -1 & 0 & 2 \end{bmatrix}$$


In [3]:
def power_method(A):
    
    X = np.ones((A.shape[0], 1), int)
    past = np.ones((A.shape[0], 1), int)
    
    epsilon = 0.000001
    n_iter = 0
    for i in range(12):
        past = X
        
        res = A.dot(X)
        largest_lambda = LA.norm(res, np.inf)
        print("Lambda: ", largest_lambda)
        res = (res / LA.norm(res, np.inf))
        X = res
        n_iter+=1
        if i > 0 and LA.norm(past - X) <= epsilon:
            break
        print("Iteration ", i, "\n",X, "\n")
    return largest_lambda, X, n_iter


#### Test

##### EX1

In [4]:
A = np.array([[-4, 14, 0],[-5, 13, 0],[-1, 0, 2]])    

In [5]:
power_method(A)

Lambda:  10.0
Iteration  0 
 [[1. ]
 [0.8]
 [0.1]] 

Lambda:  7.200000000000001
Iteration  1 
 [[ 1.        ]
 [ 0.75      ]
 [-0.11111111]] 

Lambda:  6.499999999999998
Iteration  2 
 [[ 1.        ]
 [ 0.73076923]
 [-0.18803419]] 

Lambda:  6.23076923076923
Iteration  3 
 [[ 1.        ]
 [ 0.72222222]
 [-0.22085048]] 

Lambda:  6.1111111111111125
Iteration  4 
 [[ 1.        ]
 [ 0.71818182]
 [-0.2359147 ]] 

Lambda:  6.054545454545453
Iteration  5 
 [[ 1.        ]
 [ 0.71621622]
 [-0.24309495]] 

Lambda:  6.0270270270270245
Iteration  6 
 [[ 1.        ]
 [ 0.71524664]
 [-0.24658756]] 

Lambda:  6.013452914798206
Iteration  7 
 [[ 1.        ]
 [ 0.7147651 ]
 [-0.24830578]] 

Lambda:  6.006711409395972
Iteration  8 
 [[ 1.        ]
 [ 0.71452514]
 [-0.24915656]] 

Lambda:  6.003351955307263
Iteration  9 
 [[ 1.        ]
 [ 0.71440536]
 [-0.24957942]] 

Lambda:  6.001675041876046
Iteration  10 
 [[ 1.        ]
 [ 0.71434552]
 [-0.24979007]] 

Lambda:  6.00083728718951
Iteration  11 
 [[ 

(6.00083728718951,
 array([[ 1.        ],
        [ 0.71431561],
        [-0.24989515]]),
 12)

##### EX2

In [6]:
A = np.array([[0, 2], [2, 3]])
power_method(A)

Lambda:  5.0
Iteration  0 
 [[0.4]
 [1. ]] 

Lambda:  3.8
Iteration  1 
 [[0.52631579]
 [1.        ]] 

Lambda:  4.052631578947368
Iteration  2 
 [[0.49350649]
 [1.        ]] 

Lambda:  3.987012987012987
Iteration  3 
 [[0.50162866]
 [1.        ]] 

Lambda:  4.0032573289902285
Iteration  4 
 [[0.49959317]
 [1.        ]] 

Lambda:  3.999186330349878
Iteration  5 
 [[0.50010173]
 [1.        ]] 

Lambda:  4.000203458799593
Iteration  6 
 [[0.49997457]
 [1.        ]] 

Lambda:  3.999949137887188
Iteration  7 
 [[0.50000636]
 [1.        ]] 

Lambda:  4.0000127156898895
Iteration  8 
 [[0.49999841]
 [1.        ]] 

Lambda:  3.999996821087633
Iteration  9 
 [[0.5000004]
 [1.       ]] 

Lambda:  4.000000794728724


(4.000000794728724,
 array([[0.4999999],
        [1.       ]]),
 11)